# Generated by Django 4.1.5 on 2023-01-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='analyzer_id',
            new_name='analyzer',
        ),
        migrations.RenameField(
            model_name='deviceinfield',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
